### ISSUE TITLE
monitoring module instances.cfg renamed

### ISSUE THREAD

**Issue by pather87** [saltstack-formulas/icinga2-formula#14]
The instances.ini configuration file provided by the monitoring module has been renamed to commandtransports.ini
Compare https://github.com/Icinga/icingaweb2/blob/master/doc/02-Installation.md#-upgrading-to-icinga-web-2-200

#13

**Comment by alxwr** [comment]
This has been done in 598fdf64c15094c12978c35c5412fd0822faef77. Thanks @pather87 !
