### ISSUE TITLE
Not an issue, a proposal

### ISSUE THREAD

**Issue by alxwr** [saltstack-formulas/icinga2-formula#16]
@martinhoefling @puneetk 
First of all: Thank you for sharing your code and time!

I'd like to get this formula to work with current Icinga2 on FreeBSD and Ubuntu 16.04. There seem to be many useful commits floating around on GitHub but no PRs. Instead of creating another standalone fork I'd rather work through the Issue list, fix the bugs and place my work on top of that. (So much thought went into this piece of software, work should be continued.)

What I plan on doing:
* Use the os*map pattern much like https://github.com/saltstack-formulas/openvpn-formula/blob/master/openvpn/map.jinja
* FreeBSD support
* Update pillar.example
* keep backwards compatibility

Questions I have:
* Am I welcome to do that?
* @martinhoefling is there a (technical) reason you stopped merging your ongoing development back into this formula?

Greetings
Alex

**Comment by martinhoefling** [comment]
@alexwr, sure - you're welcome to generalize the formula. I am not aware how much my personal icinga2 and saltstack formula differ.

**Comment by alxwr** [comment]
Thanks!
